project:
  type: website
  output-dir: docs

website:
  title: "UCSB SDSW"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Pages/about.qmd
        text: About
      - href: Pages/officers.qmd
        text: Officers
        
  favicon: "Images/Logos_Icons/main_logo.png"
  page-footer: "Site Originally Designed by Ethan Marzban using Quarto; ©2023"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



